version: '3'

services:
  namenode:
    image: hdfs-namenode
    ports:
      - "9000:9000"
      - "50070:50070"
    volumes:
      - ./data:/hadoop/data
    environment:
      - "HADOOP_CONF_DIR=/etc/hadoop"
      - "USER=root"
